const provinces: { [province: string]: string[] } = {
  Aceh: [
    "Kabupaten Aceh Selatan",
    "Kabupaten Aceh Tenggara",
    "Kabupaten Aceh Timur",
    "Kabupaten Aceh Tengah",
    "Kabupaten Aceh Barat",
    "Kabupaten Aceh Besar",
    "Kabupaten Pidie",
    "Kabupaten Aceh Utara",
    "Kabupaten Simeulue",
    "Kabupaten Aceh Singkil",
    "Kabupaten Bireuen",
    "Kabupaten Aceh Barat Daya",
    "Kabupaten Gayo Lues",
    "Kabupaten Aceh Jaya",
    "Kabupaten Nagan Raya",
    "Kabupaten Aceh Tamiang",
    "Kabupaten Bener Meriah",
    "Kabupaten Pidie Jaya",
    "Kota Banda Aceh",
    "Kota Sabang",
    "Kota Lhokseumawe",
    "Kota Langsa",
    "Kota Subulussalam",
  ],
  "Sumatera Utara": [
    "Kabupaten Asahan",
    "Kabupaten Batubara",
    "Kabupaten Dairi",
    "Kabupaten Deli Serdang",
    "Kabupaten Humbang Hasundutan",
    "Kabupaten Karo",
    "Kabupaten Labuhan Batu",
    "Kabupaten Labuhan Batu Selatan",
    "Kabupaten Labuhan Batu Utara",
    "Kabupaten Langkat",
    "Kabupaten Mandailing Natal",
    "Kabupaten Nias",
    "Kabupaten Nias Barat",
    "Kabupaten Nias Selatan",
    "Kabupaten Nias Utara",
    "Kabupaten Padang Lawas",
    "Kabupaten Padang Lawas Utara",
    "Kabupaten Pakpak Bharat",
    "Kabupaten Samosir",
    "Kabupaten Serdang Bedagai",
    "Kabupaten Simalungun",
    "Kabupaten Tapanuli Selatan",
    "Kabupaten Tapanuli Tengah",
    "Kabupaten Tapanuli Utara",
    "Kabupaten Toba Samosir",
    "Kota Binjai",
    "Kota Gunung Sitoli",
    "Kota Medan",
    "Kota Padangsidempuan",
    "Kota Pematang Siantar",
    "Kota Sibolga",
    "Kota Tanjung Balai",
    "Kota Tebing Tinggi",
  ],
  "Sumatera Selatan": [
    "Kabupaten Ogan Komering Ulu",
    "Kabupaten Ogan Komering Ulu Timur",
    "Kabupaten Ogan Komering Ulu Selatan",
    "Kabupaten Ogan Komering Ilir",
    "Kabupaten Muara Enim",
    "Kabupaten Lahat",
    "Kabupaten Musi Rawas",
    "Kabupaten Musi Banyuasin",
    "Kabupaten Banyuasin",
    "Kabupaten Empat Lawang",
    "Kota Ogan Ilir",
    "Kota Palembang",
    "Kota Pagar Alam",
    "Kota Lubuk Linggau",
    "Kota Prabumulih",
    "Kabupaten Panukal Abab Lematang Ilir",
    "Kabupaten Musi Rawas Utara",
  ],
  "Sumatera Barat": [
    "Kabupaten Agam",
    "Kabupaten Dharmasraya",
    "Kabupaten Kepulauan Mentawai",
    "Kabupaten Lima Puluh Kota",
    "Kabupaten Padang Pariaman",
    "Kabupaten Pasaman",
    "Kabupaten Pasaman Barat",
    "Kabupaten Pesisir Selatan",
    "Kabupaten Sijunjung",
    "Kabupaten Solok",
    "Kabupaten Solok Selatan",
    "Kabupaten Tanah Datar",
    "Kota Bukittinggi",
    "Kota Padang",
    "Kota Padangpanjang",
    "Kota Pariaman",
    "Kota Payakumbuh",
    "Kota Sawahlunto",
    "Kota Solok",
  ],
  Bengkulu: [
    "Kabupaten Bengkulu",
    "Kabupaten Bengkulu Selatan",
    "Kabupaten Bengkulu Tengah",
    "Kabupaten Bengkulu Utara",
    "Kabupaten Kaur",
    "Kabupaten Kepahiang",
    "Kabupaten Lebong",
    "Kabupaten Mukomuko",
    "Kabupaten Rejang Lebong",
    "Kabupaten Seluma",
    "Kota Bengkulu",
  ],
  Riau: [
    "Kabupaten Bengkalis",
    "Kabupaten Indragiri Hilir",
    "Kabupaten Indragiri Hulu",
    "Kabupaten Kampar",
    "Kabupaten Kepulauan Meranti",
    "Kabupaten Kuantan Singingi",
    "Kabupaten Pelalawan",
    "Kabupaten Rokan Hilir",
    "Kabupaten Rokan Hulu",
    "Kabupaten Siak",
    "Kota Dumai",
    "Kota Pekanbaru",
  ],
  "Kepulauan Riau": [
    "Kabupaten Bintan",
    "Kabupaten Karimun",
    "Kabupaten Kepulauan Anambas",
    "Kabupaten Lingga",
    "Kabupaten Natuna",
    "Kota Batam",
    "Kota Tanjung Pinang",
  ],
  Jambi: [
    "Kabupaten Bungo",
    "Kabupaten Kerinci",
    "Kabupaten Merangin",
    "Kabupaten Muaro Jambi",
    "Kabupaten Sarolangun",
    "Kabupaten Tanjung Jabung Barat",
    "Kabupaten Tanjung Jabung Timur",
    "Kabupaten Tebo",
    "Kota Jambi",
    "Kota Sungai Penuh",
  ],
  Lampung: [
    "Kabupaten Lampung Barat",
    "Kabupaten Lampung Selatan",
    "Kabupaten Lampung Tengah",
    "Kabupaten Lampung Timur",
    "Kabupaten Lampung Utara",
    "Kabupaten Mesuji",
    "Kabupaten Pesawaran",
    "Kabupaten Pesisir Barat",
    "Kabupaten Pringsewu",
    "Kabupaten Tanggamus",
    "Kabupaten Tulang Bawang",
    "Kabupaten Tulang Bawang Barat",
    "Kota Bandar Lampung",
    "Kota Metro",
  ],
  "Bangka Belitung": [
    "Kabupaten Bangka",
    "Kabupaten Bangka Barat",
    "Kabupaten Bangka Selatan",
    "Kabupaten Bangka Tengah",
    "Kabupaten Belitung",
    "Kabupaten Belitung Timur",
    "Kota Pangkal Pinang",
  ],
  "Kalimantan Barat": [
    "Kabupaten Bengkulu",
    "Kabupaten Bengkulu Selatan",
    "Kabupaten Bengkulu Tengah",
    "Kabupaten Bengkulu Utara",
    "Kabupaten Kaur",
    "Kabupaten Kepahiang",
    "Kabupaten Lebong",
    "Kabupaten Mukomuko",
    "Kabupaten Rejang Lebong",
    "Kabupaten Seluma",
    "Kota Bengkulu",
  ],
  "Kalimantan Timur": [
    "Kabupaten Berau",
    "Kabupaten Kutai Barat",
    "Kabupaten Kutai Kartanegara",
    "Kabupaten Kutai Timur",
    "Kabupaten Mahakam Ulu",
    "Kabupaten Paser",
    "Kabupaten Penajam Paser Utara",
    "Kota Balikpapan",
    "Kota Bontang",
    "Kota Samarinda",
  ],
  "Kalimantan Selatan": [
    "Kabupaten Balangan",
    "Kabupaten Banjar",
    "Kabupaten Barito Kuala",
    "Kabupaten Hulu Sungai Selatan",
    "Kabupaten Hulu Sungai Tengah",
    "Kabupaten Hulu Sungai Utara",
    "Kabupaten Kotabaru",
    "Kabupaten Tabalong",
    "Kabupaten Tanah Bumbu",
    "Kabupaten Tanah Laut",
    "Kabupaten Tapin",
    "Kota Banjarbaru",
    "Kota Banjarmasin",
  ],
  "Kalimantan Tengah": [
    "Kabupaten Barito Selatan",
    "Kabupaten Barito Timur",
    "Kabupaten Barito Utara",
    "Kabupaten Gunung Mas",
    "Kabupaten Kapuas",
    "Kabupaten Katingan",
    "Kabupaten Kotawaringin Barat",
    "Kabupaten Kotawaringin Timur",
    "Kabupaten Lamandau",
    "Kabupaten Murung Raya",
    "Kabupaten Pulang Pisau",
    "Kabupaten Sukamara",
    "Kabupaten Seruyan",
    "Kabupaten Katingan",
    "Kabupaten Barito Selatan",
    "Kabupaten Barito Timur",
    "Kabupaten Barito Utara",
    "Kabupaten Gunung Mas",
    "Kabupaten Kapuas",
    "Kabupaten Katingan",
    "Kabupaten Kotawaringin Barat",
    "Kabupaten Kotawaringin Timur",
    "Kabupaten Lamandau",
    "Kabupaten Murung Raya",
    "Kabupaten Pulang Pisau",
    "Kabupaten Sukamara",
    "Kabupaten Seruyan",
    "Kota Palangka Raya",
  ],
  "Kalimantan Utara": [
    "Kabupaten Bulungan",
    "Kabupaten Malinau",
    "Kabupaten Nunukan",
    "Kabupaten Tana Tidung",
    "Kota Tarakan",
  ],
  Banten: [
    "Kabupaten Lebak",
    "Kabupaten Pandeglang",
    "Kabupaten Serang",
    "Kabupaten Tangerang",
    "Kota Cilegon",
    "Kota Serang",
    "Kota Tangerang",
    "Kota Tangerang Selatan",
  ],
  "DKI Jakarta": [
    "Kota Jakarta Barat",
    "Kota Jakarta Pusat",
    "Kota Jakarta Selatan",
    "Kota Jakarta Timur",
    "Kota Jakarta Utara",
  ],
  "Jawa Barat": [
    "Kabupaten Bandung",
    "Kabupaten Bandung Barat",
    "Kabupaten Bekasi",
    "Kabupaten Bogor",
    "Kabupaten Ciamis",
    "Kabupaten Cianjur",
    "Kabupaten Cirebon",
    "Kabupaten Garut",
    "Kabupaten Indramayu",
    "Kabupaten Karawang",
    "Kabupaten Kuningan",
    "Kabupaten Majalengka",
    "Kabupaten Pangandaran",
    "Kabupaten Purwakarta",
    "Kabupaten Subang",
    "Kabupaten Sukabumi",
    "Kabupaten Sumedang",
    "Kabupaten Tasikmalaya",
    "Kota Bandung",
    "Kota Banjar",
    "Kota Bekasi",
    "Kota Bogor",
    "Kota Cimahi",
    "Kota Cirebon",
    "Kota Depok",
    "Kota Sukabumi",
    "Kota Tasikmalaya",
  ],
  "Jawa Tengah": [
    "Kabupaten Banjarnegara",
    "Kabupaten Banyumas",
    "Kabupaten Batang",
    "Kabupaten Blora",
    "Kabupaten Boyolali",
    "Kabupaten Brebes",
    "Kabupaten Cilacap",
    "Kabupaten Demak",
    "Kabupaten Grobogan",
    "Kabupaten Jepara",
    "Kabupaten Karanganyar",
    "Kabupaten Kebumen",
    "Kabupaten Kendal",
    "Kabupaten Klaten",
    "Kabupaten Kudus",
    "Kabupaten Magelang",
    "Kabupaten Pati",
    "Kabupaten Pekalongan",
    "Kabupaten Pemalang",
    "Kabupaten Purbalingga",
    "Kabupaten Purworejo",
    "Kabupaten Rembang",
    "Kabupaten Semarang",
    "Kabupaten Sragen",
    "Kabupaten Sukoharjo",
    "Kabupaten Tegal",
    "Kabupaten Temanggung",
    "Kabupaten Wonogiri",
    "Kabupaten Wonosobo",
    "Kota Magelang",
    "Kota Pekalongan",
    "Kota Salatiga",
    "Kota Semarang",
    "Kota Surakarta",
    "Kota Tegal",
  ],
  "Daerah Istimewa Yogyakarta": [
    "Kabupaten Bantul",
    "Kabupaten Gunung Kidul",
    "Kabupaten Kulon Progo",
    "Kabupaten Sleman",
    "Kota Yogyakarta",
  ],
  "Jawa Timur": [
    "Kabupaten Bangkalan",
    "Kabupaten Banyuwangi",
    "Kabupaten Blitar",
    "Kabupaten Bojonegoro",
    "Kabupaten Bondowoso",
    "Kabupaten Gresik",
    "Kabupaten Jember",
    "Kabupaten Jombang",
    "Kabupaten Kediri",
    "Kabupaten Lamongan",
    "Kabupaten Lumajang",
    "Kabupaten Madiun",
    "Kabupaten Magetan",
    "Kabupaten Malang",
    "Kabupaten Mojokerto",
    "Kabupaten Nganjuk",
    "Kabupaten Ngawi",
    "Kabupaten Pacitan",
    "Kabupaten Pamekasan",
    "Kabupaten Pasuruan",
    "Kabupaten Ponorogo",
    "Kabupaten Probolinggo",
    "Kabupaten Sampang",
    "Kabupaten Sidoarjo",
    "Kabupaten Situbondo",
    "Kabupaten Sumenep",
    "Kabupaten Trenggalek",
    "Kabupaten Tuban",
    "Kabupaten Tulungagung",
    "Kota Batu",
    "Kota Blitar",
    "Kota Kediri",
    "Kota Madiun",
    "Kota Malang",
    "Kota Mojokerto",
    "Kota Pasuruan",
    "Kota Probolinggo",
    "Kota Surabaya",
  ],
  Bali: [
    "Kabupaten Badung",
    "Kabupaten Bangli",
    "Kabupaten Buleleng",
    "Kabupaten Gianyar",
    "Kabupaten Jembrana",
    "Kabupaten Karangasem",
    "Kabupaten Klungkung",
    "Kabupaten Tabanan",
    "Kota Denpasar",
  ],
  "Nusa Tenggara Timur": [
    "Kabupaten Alor",
    "Kabupaten Belu",
    "Kabupaten Ende",
    "Kabupaten Flores Timur",
    "Kabupaten Kupang",
    "Kabupaten Lembata",
    "Kabupaten Malaka",
    "Kabupaten Manggarai",
    "Kabupaten Manggarai Barat",
    "Kabupaten Manggarai Timur",
    "Kabupaten Nagekeo",
    "Kabupaten Ngada",
    "Kabupaten Rote Ndao",
    "Kabupaten Sabu Raijua",
    "Kabupaten Sikka",
    "Kabupaten Sumba Barat",
    "Kabupaten Sumba Barat Daya",
    "Kabupaten Sumba Tengah",
    "Kabupaten Sumba Timur",
    "Kabupaten Timor Tengah Selatan",
    "Kabupaten Timor Tengah Utara",
    "Kota Kupang",
  ],
  "Nusa Tenggara Barat": [
    "Kabupaten Bima",
    "Kabupaten Dompu",
    "Kabupaten Lombok Barat",
    "Kabupaten Lombok Tengah",
    "Kabupaten Lombok Timur",
    "Kabupaten Lombok Utara",
    "Kabupaten Sumbawa",
    "Kabupaten Sumbawa Barat",
    "Kota Bima",
    "Kota Mataram",
  ],
  Gorontalo: [
    "Kabupaten Boalemo",
    "Kabupaten Bone Bolango",
    "Kabupaten Gorontalo",
    "Kabupaten Gorontalo Utara",
    "Kabupaten Pohuwato",
    "Kota Gorontalo",
  ],
  "Sulawesi Barat": [
    "Kabupaten Majene",
    "Kabupaten Mamasa",
    "Kabupaten Mamuju",
    "Kabupaten Mamuju Tengah",
    "Kabupaten Polewali Mandar",
  ],
  "Sulawesi Tengah": [
    "Kabupaten Banggai",
    "Kabupaten Banggai Kepulauan",
    "Kabupaten Banggai Laut",
    "Kabupaten Buol",
    "Kabupaten Donggala",
    "Kabupaten Morowali",
    "Kabupaten Parigi Moutong",
    "Kabupaten Poso",
    "Kabupaten Sigi",
    "Kabupaten Tojo Una-Una",
    "Kabupaten Tolitoli",
    "Kota Palu",
  ],
  "Sulawesi Utara": [
    "Kabupaten Bolaang Mongondow",
    "Kabupaten Bolaang Mongondow Selatan",
    "Kabupaten Bolaang Mongondow Timur",
    "Kabupaten Bolaang Mongondow Utara",
    "Kabupaten Kepulauan Sangihe",
    "Kabupaten Kepulauan Siau Tagulandang Biaro",
    "Kabupaten Kepulauan Talaud",
    "Kabupaten Minahasa",
    "Kabupaten Minahasa Selatan",
    "Kabupaten Minahasa Tenggara",
    "Kabupaten Minahasa Utara",
    "Kota Bitung",
    "Kota Kotamobagu",
    "Kota Manado",
    "Kota Tomohon",
  ],
  "Sulawesi Tenggara": [
    "Kabupaten Bombana",
    "Kabupaten Buton",
    "Kabupaten Buton Selatan",
    "Kabupaten Buton Tengah",
    "Kabupaten Buton Utara",
    "Kabupaten Kolaka",
    "Kabupaten Kolaka Timur",
    "Kabupaten Kolaka Utara",
    "Kabupaten Konawe",
    "Kabupaten Konawe Kepulauan",
    "Kabupaten Konawe Selatan",
    "Kabupaten Konawe Utara",
    "Kabupaten Muna",
    "Kabupaten Wakatobi",
    "Kota Bau-Bau",
    "Kota Kendari",
  ],
  "Sulawesi Selatan": [
    "Kabupaten Bantaeng",
    "Kabupaten Barru",
    "Kabupaten Bone",
    "Kabupaten Bulukumba",
    "Kabupaten Enrekang",
    "Kabupaten Gowa",
    "Kabupaten Jeneponto",
    "Kabupaten Kepulauan Selayar",
    "Kabupaten Luwu",
    "Kabupaten Luwu Timur",
    "Kabupaten Luwu Utara",
    "Kabupaten Maros",
    "Kabupaten Pangkajene Dan Kepulauan",
    "Kabupaten Pinrang",
    "Kabupaten Sidenreng Rappang",
    "Kabupaten Sinjai",
    "Kabupaten Soppeng",
    "Kabupaten Takalar",
    "Kabupaten Tana Toraja",
    "Kabupaten Toraja Utara",
    "Kabupaten Wajo",
    "Kota Makassar",
    "Kota Palopo",
    "Kota Parepare",
  ],
  "Maluku Utara": [
    "Kabupaten Halmahera Barat",
    "Kabupaten Halmahera Tengah",
    "Kabupaten Halmahera Timur",
    "Kabupaten Halmahera Selatan",
    "Kabupaten Halmahera Utara",
    "Kabupaten Kepulauan Sula",
    "Kabupaten Pulau Morotai",
    "Kabupaten Pulau Taliabu",
    "Kota Ternate",
    "Kota Tidore Kepulauan",
  ],
  Maluku: [
    "Kabupaten Buru",
    "Kabupaten Buru Selatan",
    "Kabupaten Kepulauan Aru",
    "Kabupaten Kepulauan Tanimbar",
    "Kabupaten Maluku Barat Daya",
    "Kabupaten Maluku Tengah",
    "Kabupaten Maluku Tenggara",
    "Kabupaten Seram Bagian Barat",
    "Kabupaten Seram Bagian Timur",
    "Kota Ambon",
    "Kota Tual",
  ],
  "Papua Barat": [
    "Kabupaten Fakfak",
    "Kabupaten Kaimana",
    "Kabupaten Manokwari",
    "Kabupaten Manokwari Selatan",
    "Kabupaten Maybrat",
    "Kabupaten Raja Ampat",
    "Kabupaten Sorong",
    "Kabupaten Sorong Selatan",
    "Kabupaten Tambrauw",
    "Kabupaten Teluk Bintuni",
    "Kabupaten Teluk Wondama",
    "Kota Sorong",
  ],
  Papua: [
    "Kabupaten Biak Numfor",
    "Kabupaten Jayapura",
    "Kabupaten Keerom",
    "Kabupaten Kepulauan Yapen",
    "Kabupaten Mamberamo Raya",
    "Kabupaten Sarmi",
    "Kabupaten Supiori",
    "Kabupaten Waropen",
    "Kota Jayapura",
  ],
  "Papua Tengah": [
    "Kabupaten Deiyai",
    "Kabupaten Dogiyai",
    "Kabupaten Intan Jaya",
    "Kabupaten Mimika",
    "Kabupaten Nabire",
    "Kabupaten Paniai",
    "Kabupaten Puncak",
    "Kabupaten Puncak Jaya",
  ],
  "Papua Pegunungan": [
    "Kabupaten Jayawijaya",
    "Kabupaten Lanny Jaya",
    "Kabupaten Mamberamo Tengah",
    "Kabupaten Nduga",
    "Kabupaten Pegunungan Bintang",
    "Kabupaten Tolikara",
    "Kabupaten Yalimo",
    "Kabupaten Yahukimo",
  ],
  "Papua Selatan": [
    "Kabupaten Asmat",
    "Kabupaten Boven Digoel",
    "Kabupaten Mappi",
    "Kabupaten Merauke",
  ],
  "Papua Barat Daya": [
    "Kabupaten Maybrat",
    "Kabupaten Raja Ampat",
    "Kabupaten Sorong",
    "Kabupaten Sorong Selatan",
    "Kabupaten Tambrauw",
    "Kota Sorong",
  ],
};

export function findAllProvince(): string[] {
  return Object.keys(provinces);
}

export function findAllCityByProvince(province: string): string[] {
  return provinces[province];
}
